### PR TITLE
Replace child_process with cross-spawn

### LINKED ISSUE #6: Windows support - can't find elm-make
Using `child_process.spawnSync` on Windows doesn't work very well, because npm generates a `.cmd` file to reference e.g. `elm` and `elm-make`, but the built-in `spawn` behavior doesn't work for `.cmd` files.  So, while I can run `elm-make` just fine from a command line, `elm-live` can't find it.  The simple fix for this is to use the [cross-spawn](https://www.npmjs.com/package/cross-spawn) package, which fixes issues with `spawn` and `spawnSync` in Windows.

### PR DESCRIPTION
**Pull request by bdukes**
Fixes #6

While this allows elm-live to find elm-make, it looks like there's still some other issue, as I'm not getting any watching or browser opening when I try to use it.  Anyway, hope it helps.

### CODE REVIEW

**Comment by tomekwi** [comment]
Hi, thanks again for your valuable contributions. It would be great to have Windows support as well! Do you want to stay with me and push this through together? I don’t have a Windows box to test things out anymore.

cross-spawn looks like a useful project. Can you please rebase and get the build to pass? I’ll be delighted to merge this.

As for your other problems, I’ve updated https://git.io/gaze to a new version – does this resolve the watching problem? Opening the browser is done directly by https://git.io/budo-server – does it work directly with `budo --open` for you?

**Comment by bdukes** [comment]
I've rebased, and also fixed a path issue so that the tests pass on my machine

**Comment by bdukes** [comment]
The new gaze didn't seem to make a difference.  Running `budo --open` directly does work just fine.

**Comment by tomekwi** [comment]
Thanks a lot for the PR and rebase! I made a small change – I reversed the path logic in @327e445, because `path.relative` is what we use in the program itself. It’s better to `assert.equal(2 + 2, 4)` than `assert.equal(2 + 2, 2 + 2)`.

I’m a big fan of http://openopensource.org/. Your contributions are very valuable, so I’m delighted to make you a collaborator on the repo. :beers:

**Comment by tomekwi** [comment]
@bdukes By the way, please continue to use the Pull Request workflow for any non-trivial changes. I will do so as well from now on.

**Pull request merged**
